const data =
  [
    {
      "Name": "Adarsh ​​Kumar",
      "Phone": "8709766103",
      "Email I'd": "adarshkumar.ak90@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Shikha Kumari Singh",
      "Phone": "7488151751",
      "Email I'd": "shikha004.singh@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Amit Kumar",
      "Phone": "8563063454",
      "Email I'd": "amitkr0796@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Randhir Kumar",
      "Phone": "9835250101",
      "Email I'd": "ydv_randhir@outlook.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Sagar Singh",
      "Phone": "8173031454",
      "Email I'd": "sagarsiwan931@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Apoorva Aditya",
      "Phone": "8384014567",
      "Email I'd": "adityaapoorva010@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Vishal Prasad",
      "Phone": "8509565571",
      "Email I'd": "vishalp98.vp@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Manish Shukla",
      "Phone": "9654457152",
      "Email I'd": "4mshukla@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Pooja Kumari",
      "Phone": "7044659090",
      "Email I'd": "pujasah690@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Kumar Bala ji",
      "Phone": "8969414518",
      "Email I'd": "kumarbalajee100@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Shiva Shubham",
      "Phone": "7909055653",
      "Email I'd": "shubhamshiv18@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Savitri Sharma",
      "Phone": "9588003393",
      "Email I'd": "savitrisharma9490@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Aniket Kumar",
      "Phone": "7982851405",
      "Email I'd": "aniketkumar835@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Chandrakant Suman",
      "Phone": "8051776514",
      "Email I'd": "chandrakantsuman@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Preeti Kumari",
      "Phone": "9065889205",
      "Email I'd": "pritisingh97799@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Mamta Kumari",
      "Phone": "9821070765",
      "Email I'd": "mamtaupsc10@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Deepak Kumar",
      "Phone": "9015244637",
      "Email I'd": "deepak.dk.1998@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Preeti Kumari",
      "Phone": "9205772659",
      "Email I'd": "priti.pathak878@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Ehsaan Ahmed",
      "Phone": "9595042402",
      "Email I'd": "ehsanahmad78626@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Aditi Kumari",
      "Phone": "7321927789",
      "Email I'd": "aditi3920@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Abhishek Jha",
      "Phone": "8757475424",
      "Email I'd": "pikkujha44@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Shubham Kumar",
      "Phone": "9852838115",
      "Email I'd": "skshanu96@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Rakesh Kumar",
      "Phone": "7858071663",
      "Email I'd": "rk771212@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Nitish Kumar",
      "Phone": "8210314953",
      "Email I'd": "nitishkumar464h@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Anisha Kumari",
      "Phone": "7011687746",
      "Email I'd": "nirmalanishu11@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Sapna Kumari",
      "Phone": "7903451976",
      "Email I'd": "sapnaswarniya@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Rahul",
      "Phone": "9999397546",
      "Email I'd": "rahul.avhi49@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Ankita Singh",
      "Phone": "9572021005",
      "Email I'd": "ask.ankitas@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Amardeep Kumar Mukhiya",
      "Phone": "7982656618",
      "Email I'd": "amardeep94kumar@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Anshu Kumari",
      "Phone": "6299180799",
      "Email I'd": "anshupandey40@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Paritosh",
      "Phone": "8969405501",
      "Email I'd": "paritosh.weed@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Pushpanjali",
      "Phone": "9573519806",
      "Email I'd": "pushpanjalis365@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Shemushi Kumari",
      "Phone": "6201486209",
      "Email I'd": "mehar62014@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Shadma Shaukat",
      "Phone": "9709435548",
      "Email I'd": "shadma241@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Ayushi Kumari",
      "Phone": "7004961841",
      "Email I'd": "aayushi.kumari1602@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Swarna Surbhi",
      "Phone": "6202696187",
      "Email I'd": "swarnasurbhi21@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Satya Prakash Gautam",
      "Phone": "7568015711",
      "Email I'd": "jugnuanup@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Priyaranjan Rahul",
      "Phone": "9801391478",
      "Email I'd": "rahulind828@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Manish Kumar",
      "Phone": "9711685870",
      "Email I'd": "kumar251290manish@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Vishal Kumar Singh",
      "Phone": "6205719583",
      "Email I'd": "Iamvishal720@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Chandan Kumar",
      "Phone": "9931465681",
      "Email I'd": "chandankumardobhi286@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Rahul Kumar",
      "Phone": "7858037280",
      "Email I'd": "rahulkanti400@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Raj Kishore Pandit",
      "Phone": "8864815501",
      "Email I'd": "kishorbihar123@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Saurabh Suman",
      "Phone": "9155449106",
      "Email I'd": "sauravsuman2812@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "avinash kumar",
      "Phone": "9811060475",
      "Email I'd": "avi.du92@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Prashant Raj",
      "Phone": "7903984243",
      "Email I'd": "prashant.pr.raj@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "vivek kumar hati",
      "Phone": "6299025082",
      "Email I'd": "vkraj20898@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Divyani",
      "Phone": "7545947367",
      "Email I'd": "vashishthdivya128@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Om Prakash",
      "Phone": "9311498817",
      "Email I'd": "omsingh4702@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Ripudaman",
      "Phone": "7319930955",
      "Email I'd": "ripu.rdk@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Shravan Kumar Chaudhary",
      "Phone": "8271969762",
      "Email I'd": "shravankumar8277@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Yusuf Jameel",
      "Phone": "7762892469",
      "Email I'd": "yusuf.jamil786@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Ashutosh Kumar",
      "Phone": "9661504271",
      "Email I'd": "ashu.kumar626@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Utpal Kumar",
      "Phone": "8810421881",
      "Email I'd": "utpalmishra31@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Abhishek Ranjan",
      "Phone": "9508892430",
      "Email I'd": "siyaramchandra31@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Vivek Kumar",
      "Phone": "8210373184",
      "Email I'd": "rvivek8210@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "avinash kumar",
      "Phone": "8340501878",
      "Email I'd": "aviraj.rajput666@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Nusrat Praveen",
      "Phone": "7766811067",
      "Email I'd": "nusratparween145@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Chandrashekhar Singh",
      "Phone": "9934412727",
      "Email I'd": "cssingh367@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Ritu Kumari",
      "Phone": "8102787481",
      "Email I'd": "rit12091998@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Gulnaz Khatun",
      "Phone": "7033316861",
      "Email I'd": "gunazg314@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Ranjit Tanti",
      "Phone": "8581994085",
      "Email I'd": "ranjitkumartanti3@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Deepak Raj",
      "Phone": "8076269827",
      "Email I'd": "rdeepak337@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 1",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Prashansa",
      "Phone": "6203272850",
      "Email I'd": "prashansha2111@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Lakhan Kumar Tanti",
      "Phone": "7562086671",
      "Email I'd": "rajlakhantanti329@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Sakshi Priya",
      "Phone": "7004153364",
      "Email I'd": "sakshi909752@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Prashant Kumar",
      "Phone": "9559762255",
      "Email I'd": "prashantkr.iitk@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Rakesh Kumar",
      "Phone": "8051566073",
      "Email I'd": "rakeshkumarbgp20@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Indrajit Kumar",
      "Phone": "8002434047",
      "Email I'd": "indrajeetkumar42875@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Premdeep Gehlot",
      "Phone": "7065802229",
      "Email I'd": "thenameisprem003@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Rashmi Rekha",
      "Phone": "9142547857",
      "Email I'd": "rashmiunique3329@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Akhilesh Kumar",
      "Phone": "9304579641",
      "Email I'd": "akkibhu93@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Deepak Kumar",
      "Phone": "9304691801",
      "Email I'd": "dk66424@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Mamta Kumari",
      "Phone": "7544050797",
      "Email I'd": "m.k9160073@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Sanjeet Kumar Rajak",
      "Phone": "9939359105",
      "Email I'd": "sanjeetbanty@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Sujay Kumar",
      "Phone": "9939514240",
      "Email I'd": "sujaykumar140197@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Ashwini Kumar",
      "Phone": "9934687364",
      "Email I'd": "dih.ashvini@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Jitendra Kumar",
      "Phone": "8521027150",
      "Email I'd": "jitendrakr824115@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Kumari Ranju Bharti",
      "Phone": "9911677289",
      "Email I'd": "krb16021991@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Khushboo Gauri",
      "Phone": "7033960710",
      "Email I'd": "gourikhushbu.khushi@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Priyanka Kumari",
      "Phone": "7366882244",
      "Email I'd": "amit.krara@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Suman Kumari",
      "Phone": "9716555501",
      "Email I'd": "suman555501@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Vicky Kumar",
      "Phone": "7004801361",
      "Email I'd": "vickumar591@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Vandana Kumari",
      "Phone": "6206694561",
      "Email I'd": "vanduk787@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Vipul Kumar",
      "Phone": "8863041068",
      "Email I'd": "bipulkumar295@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Krishna Kumar",
      "Phone": "9354106270",
      "Email I'd": "krishnayzkumar@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Aditi Parimal",
      "Phone": "6204766836",
      "Email I'd": "adityparimal@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Rajneesh Kumar",
      "Phone": "9540750677",
      "Email I'd": "rajnishprasad166bitu@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Abhijit Kumar Gupta",
      "Phone": "9304878025",
      "Email I'd": "thisabhijeet123@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Swati Suman",
      "Phone": "7004703339",
      "Email I'd": "swatisuman50005@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Pankaj Kumar Ram",
      "Phone": "6206534202",
      "Email I'd": "ktrpankajkumar3051@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Jitendra Kumar",
      "Phone": "7701905320",
      "Email I'd": "jeetgupta.em@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Sachin Kumar",
      "Phone": "7050192886",
      "Email I'd": "sachinkumar5695@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Akanksha Ranjan",
      "Phone": "9113177079",
      "Email I'd": "ksushma613@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Shashank Sagar",
      "Phone": "7634015710",
      "Email I'd": "shashanksagar28@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Sudhanshu Kumar Singh",
      "Phone": "9155421111",
      "Email I'd": "sudhu5282@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Neelu Kumari",
      "Phone": "6207452238",
      "Email I'd": "nilukumari0251@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Vishakha Patel",
      "Phone": "8757690398",
      "Email I'd": "patel.vishakhaa@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Abhay Kishore",
      "Phone": "7352656439",
      "Email I'd": "abhaykishor3@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Sameer Haider",
      "Phone": "6201923765",
      "Email I'd": "sameerhaiderbhr@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Nilgiri",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Kanchan Kumari",
      "Phone": "8252837908",
      "Email I'd": "kanchan13898@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Kumari Smita",
      "Phone": "9973708907",
      "Email I'd": "smita14885@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Mohd. Safi Alam",
      "Phone": "9760290998",
      "Email I'd": "salam0735@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Meraj Ahmed",
      "Phone": "7859845837",
      "Email I'd": "mail.miraj.ahmad@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Dayanand Sharma",
      "Phone": "7277518183",
      "Email I'd": "dayasharma0810@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Nandan Kumar",
      "Phone": "9631542653",
      "Email I'd": "nandank12599@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Prabhakar Kumar",
      "Phone": "6202414445",
      "Email I'd": "pkak@outlook.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Rahul Kumar",
      "Phone": "9810410235",
      "Email I'd": "rahul.k20@mibdu.org",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Sweta Bharti",
      "Phone": "7488970618",
      "Email I'd": "bhartisweta6398@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Praveen Kumar Singh",
      "Phone": "7319810288",
      "Email I'd": "praveenksteacher@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Ravi Raj",
      "Phone": "8709443635",
      "Email I'd": "monukarkare@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Pranjal Patel",
      "Phone": "6201116152",
      "Email I'd": "pranjalpatelds@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Prashant Kumar Soni",
      "Phone": "8757326128",
      "Email I'd": "prashant.rajaspl@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Aastha Sinha",
      "Phone": "9934356938",
      "Email I'd": "aasthasinha2808@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Niresh Kumari",
      "Phone": "7073196890",
      "Email I'd": "hi.nishu16@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Ankit Kumar",
      "Phone": "8076786897",
      "Email I'd": "ankitary70@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Sujit Kumar",
      "Phone": "8826227858",
      "Email I'd": "sujeet.ind14@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Manish Kumar",
      "Phone": "9958578414",
      "Email I'd": "kumarmanish940322@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Sardar Gurupreet Singh",
      "Phone": "9123129203",
      "Email I'd": "sardargurupritsingh@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Alok Kumar Singh",
      "Phone": "7319810287",
      "Email I'd": "alokteacherpatla@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Pooja Kumari",
      "Phone": "9560450778",
      "Email I'd": "pujayadav19982303@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Vijaya Lakshmi",
      "Phone": "9361628430",
      "Email I'd": "elizavijya@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Aakriti Kumari",
      "Phone": "9304941586",
      "Email I'd": "aakriti7531@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Swati Sushanthi",
      "Phone": "8271565075",
      "Email I'd": "swatisushanti41@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Rashmi Kumari",
      "Phone": "7004693118",
      "Email I'd": "rashmik258@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    },
    {
      "Name": "Vijeta kumari gupta",
      "Phone": "9693337561",
      "Email I'd": "11vijeta@gmail.com",
      "Designation": "Assistant Audit Officer",
      "Batch": "Group 2",
      "Hostel": "Arawali",
      "Mess": "Sujata Mess",
      "admin": "Mr. Aditya Jaiswal",
      "admin_ph": 7870312552,
      "Coordinater": "Mr. Abhudaya"
    }
  ]

export default data;